/**
 * English marketing copy - source deck for product messaging.
 * Keep `messages/en.json` → `Home` (and related keys) aligned with this file;
 * Polish lives only in `messages/pl.json`.
 */
export const landingHome = {
  skipToContent: "Skip to content",
  eyebrow: "Portfolio intelligence · iOS",
  headline: "Portfolio tracker and analytics for serious investors.",
  heroProof1: "Portfolio tracking",
  heroProof2: "Portfolio analytics",
  heroProof3: "Investment intelligence",
  subhead:
    "Import holdings from your brokers, analyze allocation and risk, and get explained insights on mobile—without sharing broker passwords.",
  heroPrimaryCta: "Start tracking your portfolio",
  heroSecondaryCta: "Join early access",
  heroTertiaryCta: "See market data stack",
  heroFootnote: "Operated by Jakub Gruszczyk QBKSHOP · Early-stage · iOS live",
  heroImageAlt:
    "Alpha Investor screen showing five lenses: trend, valuation, risk, growth, and momentum.",
  heroDeckWalletAlt: "Portfolio view with allocation and performance.",
  heroDeckChartAlt: "Instrument detail with chart and performance.",
  trustItem1: "Broker file imports",
  trustItem2: "Licensed market data",
  trustItem3: "Privacy-first",
  trustItem4: "Not investment advice",
  trustBrokersLine:
    "Also supports Robinhood, mBank eMakler, and other CSV/Excel exports.",
  importsTitle: "Portfolio imports",
  importsIntro:
    "Import portfolios from your broker and start analyzing your investments in minutes.",
  importsBody:
    "No broker login. No API credentials. Upload an export file—we map positions, validate symbols, and build your book on licensed market data.",
  importsStep1Title: "Upload file",
  importsStep1Body: "Export open positions or history from your broker (CSV or Excel).",
  importsStep2Title: "Automatic mapping",
  importsStep2Body: "We detect broker format and map columns to a unified portfolio model.",
  importsStep3Title: "Portfolio created",
  importsStep3Body: "Holdings, currencies, and lots appear in one mobile-native book.",
  importsStep4Title: "Analytics available",
  importsStep4Body: "Allocation, performance, lenses, and explained insights turn on immediately.",
  importsCta: "See how it works",
  importsCtaSecondary: "Join early access",
  brokerXtb: "XTB",
  brokerIbkr: "Interactive Brokers",
  brokerDegiro: "DEGIRO",
  brokerT212: "Trading 212",
  brokerRevolut: "Revolut",
  brokerCsv: "Custom CSV",
  brokerRobinhood: "Robinhood",
  brokerMbank: "mBank eMakler",
  whyNowEyebrow: "Why now",
  whyNowTitle: "More data. Same hard decisions.",
  whyNowIntro:
    "Retail investors have more information than ever—and more brokers, apps, and charts than they can reconcile. Information alone does not improve decisions without context tied to your book.",
  whyNowProblem1Title: "Data overload",
  whyNowProblem1Body:
    "Quotes, news, and screens multiply. Portfolio truth stays fragmented across accounts.",
  whyNowProblem2Title: "Fragmented brokers",
  whyNowProblem2Body:
    "Holdings live in silos. No single place shows total exposure, concentration, or performance.",
  whyNowProblem3Title: "Missing context",
  whyNowProblem3Body:
    "Numbers without explanation do not tell you what to focus on—or why it matters now.",
  whyNowResolution:
    "Alpha Investor is building the portfolio intelligence layer: imports that unify your book, market data that enriches every line, and explained analytics that turn data into decisions you can defend.",
  whyNowCta: "Explore the platform",
  platformTitle: "One engine for portfolio tracking and analysis",
  platformIntro:
    "Alpha Investor is not a watchlist app. It is infrastructure that turns fragmented broker exports into a single, analyzable book.",
  platformPillar1Title: "Connect your brokers",
  platformPillar1Body:
    "Import open positions and history from broker exports. No live broker credentials — your files are processed with privacy-first controls.",
  platformPillar2Title: "Enrich with market data",
  platformPillar2Body:
    "Server-side quotes, reference fields, and symbol validation power charts and analytics for every holding.",
  platformPillar3Title: "Understand with explained insights",
  platformPillar3Body:
    "Allocation, performance, risk lenses, and AI readouts weighted to your actual portfolio — every signal with reasoning.",
  platformCta: "See broker imports",
  dataEyebrow: "Infrastructure",
  dataTitle: "Market data infrastructure",
  dataIntro:
    "Alpha Investor is built on licensed market data APIs. Each connected portfolio drives recurring consumption across pricing, fundamentals, and instrument resolution—the same primitives institutional platforms depend on.",
  dataStatLine:
    "Every portfolio sync triggers quote, reference, and validation workloads at scale.",
  dataGrid1Title: "Historical prices",
  dataGrid1Body: "Time-series and performance context for every holding and portfolio view.",
  dataGrid2Title: "Company fundamentals",
  dataGrid2Body: "Reference fields that power valuation lenses and explained factor readouts.",
  dataGrid3Title: "ETF & instrument metadata",
  dataGrid3Body: "Identifiers and classification for mixed equity and fund books.",
  dataGrid4Title: "Instrument discovery",
  dataGrid4Body: "Search and symbol validation across US, European, and exchange-qualified listings.",
  dataGrid5Title: "Portfolio analytics",
  dataGrid5Body: "Server-side enrichment for allocation, risk concentration, and cross-broker exposure.",
  dataGrid6Title: "Market-wide coverage",
  dataGrid6Body: "Designed for high-cardinality retail books—many symbols per user, many users over time.",
  dataPartnerCta: "Data & API partnerships",
  dataFooterLine:
    "We do not resell raw data. We consume licensed feeds to deliver portfolio intelligence to end users.",
  dataVendorsLink: "For data vendors",
  engineTitle: "Investment intelligence beyond a portfolio tracker",
  engineIntro:
    "More than a stock portfolio tracker. Alpha Investor applies a consistent analytics layer across your real weights—not a generic watchlist.",
  engineCap1Title: "Portfolio allocation",
  engineCap1Body: "Sector, geography, and position weights with drift signals.",
  engineCap2Title: "Risk concentration",
  engineCap2Body: "Exposure and concentration flags tied to your book.",
  engineCap3Title: "Valuation",
  engineCap3Body: "Fundamentals-style context and valuation lens scores.",
  engineCap4Title: "Quality",
  engineCap4Body: "Business quality factors surfaced with plain-language rationale.",
  engineCap5Title: "Growth",
  engineCap5Body: "Growth lens scores comparable across every holding.",
  engineCap6Title: "Momentum",
  engineCap6Body: "Trend and momentum context on charts and scores.",
  engineAiTitle: "AI-generated insights",
  engineAiBody:
    "Explained readouts on what changed, why it matters, and which factors drove the signal—weighted to your portfolio.",
  engineCta: "See portfolio insights",
  aiProBadge: "Alpha Pro",
  aiExplain: "You see what changed, why it matters, and where to focus next.",
  aiProHook: "No black box. Every signal is explained so you can decide with confidence.",
  aiPillar1Title: "What is this?",
  aiPillar1Body: "Explained analytics and AI readouts on top of your real portfolio weights.",
  aiPillar2Title: "Why it matters",
  aiPillar2Body: "You get context tied to your book — not isolated numbers or generic watchlists.",
  aiPillar3Title: "What should I do?",
  aiPillar3Body: "Use each explained signal to choose your next step — you stay in control.",
  benefitsTitle: "Why investors choose our portfolio analysis app",
  benefitsIntro: "Outcomes that matter when you manage real money across brokers.",
  benefit1Title: "See total exposure across brokers",
  benefit1Body: "One view of allocation and performance when holdings live in multiple accounts.",
  benefit2Title: "Know concentration and allocation drift",
  benefit2Body: "Plain-language signals on mix and concentration — meant to inform, not panic.",
  benefit3Title: "Compare holdings on a consistent model",
  benefit3Body: "The same five-lens scale on every ticker with rationale you can scan in seconds.",
  benefit4Title: "Act on explained signals",
  benefit4Body: "Every score links to factors behind it — no black-box predictions or hype.",
  benefit5Title: "Mobile-first portfolio review",
  benefit5Body: "Charts, fundamentals-style context, and AI in one flow — not six browser tabs.",
  benefitsCta: "Start tracking your portfolio",
  trustTitle: "Trust, security, and data handling",
  trustIntro: "Your portfolio data is sensitive. We designed imports and analytics so you stay in control.",
  trustSecurityTitle: "Security",
  trustSecurityBody:
    "No broker credentials required. We never ask for your brokerage password or OAuth trading access.",
  trustPrivacyTitle: "Privacy",
  trustPrivacyBody:
    "Insights are generated for your account. We do not train public foundation models on your portfolio.",
  trustProcessingTitle: "File processing",
  trustProcessingBody:
    "Broker export files are processed with privacy-first controls; parsing happens on-device where the product architecture allows.",
  trustInfrastructureTitle: "Infrastructure",
  trustInfrastructureBody:
    "Encrypted transport, access controls, and vendor due diligence for server-side market data.",
  trustComplianceTitle: "Compliance",
  trustComplianceBody: "Educational software only—not investment, tax, or legal advice.",
  trustPrivacyCta: "Read privacy policy",
  scaleTitle: "Built for scale",
  scaleIntro:
    "We are an early-stage team building infrastructure that must work for one portfolio—and for millions. Usage compounds: every import adds symbols; every refresh adds market data workloads; every insight adds compute on top of deterministic portfolio math.",
  scaleBullet1: "Multi-broker ecosystem across regions and currencies",
  scaleBullet2: "Global equities and ETFs in one analytics model",
  scaleBullet3: "Portfolio intelligence APIs consumed at session and sync scale",
  scaleBullet4: "AI research tools layered on explained analytics—not replacing them",
  scaleBullet5: "International expansion as imports and data partnerships grow",
  scaleCta: "Partner with us",
  scaleCtaSecondary: "Join early access",
  featuresTitle: "What you can do",
  featuresIntro: "Portfolios, charts, and explained readouts in one steady flow.",
  feature1Title: "Wallet health & allocation",
  feature1Body: "Plain-language heads-up on mix and concentration across your book.",
  feature2Title: "Five lens scores",
  feature2Body:
    "Same scale on every ticker with a line of rationale — compare quickly without building your own factor sheet.",
  feature3Title: "Instrument deep dive",
  feature3Body:
    "Chart, performance, fundamentals-style context, and narrative readouts in one scroll.",
  feature4Title: "Portfolios, privacy, live data",
  feature4Body:
    "Multiple books and lots, server-backed quotes, and insights for your account only.",
  stepsTitle: "How portfolio tracking works",
  step1Title: "Import or add your book",
  step1Body:
    "Import a broker export (XTB, IBKR, DEGIRO, and more) or create a portfolio manually with your positions and base currency.",
  step2Title: "We enrich every holding",
  step2Body:
    "Charts, quotes, reference fields, and symbol validation pull from licensed market data on the server.",
  step3Title: "Review explained insights",
  step3Body:
    "Use wallet and per-name readouts as a brief: what looks stretched, what looks balanced — then decide on your terms.",
  stepsCta: "Get the iOS app",
  stepsCtaSecondary: "Join early access",
  pricingEyebrow: "Pricing",
  pricingTitle: "Portfolio tracker plans and pricing",
  pricingTagline: "$10/month for the full explained intelligence layer on your portfolio.",
  pricingFreeName: "Free",
  pricingFreePrice: "$0",
  pricingFreeBullet1: "Portfolios, live quotes, and charts — without premium AI readouts.",
  pricingFreeBullet2: "Same account privacy — nothing is trained on your book for public models.",
  pricingFreeBullet3: "Upgrade under Settings → Subscription on iOS when you are ready.",
  pricingProName: "Alpha Pro",
  pricingProBadge: "Full AI",
  pricingProPrice: "$10",
  pricingProPeriod: "/ month",
  pricingProBullet1: "Wallet + every holding narrated off YOUR weights — not a generic watchlist.",
  pricingProBullet2: "Five lenses on every ticker with plain-English rationale you can scan in seconds.",
  pricingProBullet3: "Instrument screen: chart, fundamentals-style context, and AI in one scroll.",
  pricingProBullet4: "Future Pro-only features ship here first.",
  pricingCtaPrimary: "Start with Free",
  pricingCtaSecondary: "See portfolio insights",
  pricingDisclaimerLine:
    "Educational software only — markets stay risky. We sell clarity on your own data, not promises of returns.",
  pricingFootnote:
    "Purchases run inside the Alpha Investor app via Apple In-App Purchase on iOS (price may vary by region). Google Play billing is on the roadmap. Cancel from your device subscription settings.",
  screensTitle: "Stock portfolio tracker — mobile product tour",
  screensIntro: "Portfolio tracking, charts, and explained signals — designed for mobile.",
  screensCta: "View pricing",
  screensCtaSecondary: "Join early access",
  galleryPortfolioInsightKicker: "Explained signals",
  galleryWalletValueKicker: "Performance",
  galleryWalletAllocationKicker: "Allocation",
  galleryChartKicker: "Momentum",
  galleryFiveLensesKicker: "Comparison",
  galleryFundamentalsKicker: "Valuation",
  galleryOptimizerKicker: "Scenario",
  galleryNewsKicker: "News",
  galleryWalletValueTitle: "See if your plan is working",
  galleryWalletValueBody:
    "Portfolio value over time with simple range controls — see the arc without jumping between tools.",
  galleryWalletAllocationTitle: "Understand what you own",
  galleryWalletAllocationBody: "See allocation, exposure, and performance in one place.",
  galleryPortfolioInsightTitle: "Explained portfolio insight",
  galleryPortfolioInsightBody: "Clear signals with context — every score with reasoning.",
  galleryChartTitle: "Read the market",
  galleryChartBody: "Charts and signals, simplified.",
  galleryFiveLensesTitle: "Break it down",
  galleryFiveLensesBody: "Trend, valuation, growth, risk, and momentum in one view.",
  galleryFundamentalsTitle: "See the reasoning",
  galleryFundamentalsBody: "Every signal links to the factors behind it.",
  galleryOptimizerTitle: "Plan your next move",
  galleryOptimizerBody: "Test changes before you act on your portfolio.",
  galleryNewsTitle: "Track what matters",
  galleryNewsBody: "Use market context to filter noise and focus on decisions.",
  faqTitle: "Frequently asked questions",
  faq1Q: "Is this financial advice?",
  faq1A:
    "No. Alpha Investor is software plus educational context. We are not a fiduciary and do not know your full finances — you stay in charge of trades and taxes.",
  faq2Q: "How do broker imports work?",
  faq2A:
    "Export open positions or history from your broker (CSV/Excel where supported), then import in the app. We do not connect to your broker with your login — file-based imports only.",
  faq3Q: "Which brokers are supported?",
  faq3A:
    "Import templates for XTB, Interactive Brokers, DEGIRO, Trading 212, Revolut, Robinhood, mBank eMakler, plus a generic path for other CSV/Excel exports. Coverage expands over time.",
  faq4Q: "Where does market data come from?",
  faq4A:
    "Licensed market data providers on our servers — quotes, reference fields, and symbol validation. We do not use other users' portfolio data as a data source.",
  faq5Q: "What does the AI add?",
  faq5A:
    "Explained readouts on your wallet and holdings — what changed, why it matters, and factors behind each signal. Alpha Pro adds the full layer across your book.",
  faq6Q: "Which platforms are supported?",
  faq6A: "iOS today. Android is on the roadmap — join the waitlist for timing.",
  faq7Q: "How does pricing work?",
  faq7A:
    "Free includes portfolios, quotes, and charts without premium AI. Alpha Pro is $10/month for full explained intelligence — subscribe in the iOS app via the App Store.",
  faq8Q: "Do you train public models on my portfolio?",
  faq8A:
    "No. Insights are generated for your account from your data and licensed feeds under our privacy terms.",
  faq9Q: "What happens after I join the waitlist?",
  faq9A: "Occasional email about releases and Android timing. Unsubscribe anytime.",
  faq10Q: "Are you a broker or custodian?",
  faq10A:
    "No. We do not hold assets, route orders, or provide personalized investment advice. You manage trades at your brokers.",
  faq11Q: "I'm a data or API provider — how do we partner?",
  faq11A:
    "Email partners@alphainvestor.app with your data products and use cases. We consume quotes, reference data, and symbol validation at portfolio scale.",
  faq12Q: "Is my data secure?",
  faq12A:
    "We design for privacy-first imports (no broker passwords), account-scoped insights, and standard security practices. See our Privacy policy and in-app notices for details.",
  ctaTitle: "Start with your real portfolio",
  ctaSub: "Download on iOS or join early access for Android and major releases.",
  formConsent: "By joining, you agree we may email you about the product. See",
  formConsentLink: "Privacy",
  disclaimer:
    "Not investment, tax, or legal advice. AI text can be incomplete or stale — double-check anything that would change your money.",
  roadmapTitle: "Platform roadmap",
  roadmapIntro:
    "Strategic capabilities we are building toward—order may change; no dates implied.",
  roadmapFootnote: "Roadmap describes direction, not commitments or timelines.",
  roadmapPhase1Title: "Portfolio tracking",
  roadmapPhase1Badge: "In progress",
  roadmapPhase1Body:
    "Unified books, live quotes, charts, and performance across holdings. iOS is live today.",
  roadmapPhase2Title: "Broker connectivity",
  roadmapPhase2Body:
    "Broader import templates, symbol resolution, and multi-account workflows.",
  roadmapPhase3Title: "Portfolio intelligence",
  roadmapPhase3Body:
    "Allocation, risk, lenses, and explained analytics across the full book.",
  roadmapPhase4Title: "AI research layer",
  roadmapPhase4Body:
    "Deeper explained insights and research workflows on top of portfolio truth.",
  roadmapPhase5Title: "Investment operating system",
  roadmapPhase5Body:
    "Multi-broker, multi-asset platform for tracking, analysis, and decision support at scale.",
  roadmapCta: "Join early access",
} as const;
