/**
 * English marketing copy - source deck for product messaging.
 * Keep `messages/en.json` → `Home` (and related keys) aligned with this file;
 * Polish lives only in `messages/pl.json`.
 */
export const landingHome = {
  skipToContent: "Skip to content",
  ctaPrimary: "Join Early Access",
  ctaSecondary: "Learn More",
  eyebrow: "Portfolio analytics · iOS",
  headline: "Know what to do.",
  subheadCategory: "Portfolio tracking and analytics for long-term investors.",
  subheadBenefit:
    "Track your portfolio, understand what changed, and make better investment decisions.",
  heroPrimaryCta: "Join Early Access",
  heroSecondaryCta: "Learn More",
  heroImageAlt:
    "Alpha Investor screen showing five lenses: trend, valuation, risk, growth, and momentum.",
  heroDeckWalletAlt: "Portfolio view with allocation and performance.",
  heroDeckChartAlt: "Instrument detail with chart and performance.",
  trustItem1: "Broker file imports",
  trustItem2: "Licensed market data",
  trustItem3: "Privacy-first",
  trustItem4: "Not investment advice",
  importsTitle: "Import your portfolio in minutes",
  importsIntro:
    "Upload a broker export and start tracking your investments instantly.",
  importsStep1Title: "Upload file",
  importsStep1Body: "Export from your broker - we map positions automatically.",
  importsStep2Title: "Portfolio created",
  importsStep2Body: "Your holdings appear in one book.",
  importsStep3Title: "Analytics available",
  importsStep3Body: "Allocation, performance, and insights turn on.",
  brokerXtb: "XTB",
  brokerIbkr: "Interactive Brokers",
  brokerDegiro: "DEGIRO",
  brokerT212: "Trading 212",
  brokerRevolut: "Revolut",
  brokerCsv: "Custom CSV",
  platformTitle: "Portfolio tracking and analysis",
  platformIntro: "One book from broker exports - not a generic watchlist.",
  platformPillar1Title: "Connect your brokers",
  platformPillar1Body: "Import via export files. No broker passwords.",
  platformPillar2Title: "Enrich with market data",
  platformPillar2Body: "Quotes and reference data for every holding.",
  platformPillar3Title: "Understand with insights",
  platformPillar3Body: "Allocation, risk lenses, and signals on your weights.",
  dataEyebrow: "Infrastructure",
  dataTitle: "Market data infrastructure",
  dataIntro: "Licensed APIs power quotes, fundamentals, and validation for every portfolio.",
  dataGrid1Title: "Historical prices",
  dataGrid1Body: "Performance context for holdings and your book.",
  dataGrid2Title: "Company fundamentals",
  dataGrid2Body: "Reference data for valuation lenses.",
  dataGrid3Title: "ETF metadata",
  dataGrid3Body: "Classification for equity and fund holdings.",
  dataGrid4Title: "Instrument discovery",
  dataGrid4Body: "Search and validate symbols across major listings.",
  dataGrid5Title: "Portfolio analytics",
  dataGrid5Body: "Allocation and risk enrichment on the server.",
  dataGrid6Title: "Market-wide coverage",
  dataGrid6Body: "Built for diversified books and scale as users grow.",
  dataPartnerCta: "Data & API partnerships",
  dataVendorsLink: "For data vendors",
  engineTitle: "Portfolio intelligence",
  engineIntro: "Analytics on your real weights - not a generic watchlist.",
  engineCap1Title: "Portfolio allocation",
  engineCap1Body: "Weights and drift across sectors and positions.",
  engineCap2Title: "Risk concentration",
  engineCap2Body: "Exposure flags tied to your book.",
  engineCap3Title: "Valuation",
  engineCap3Body: "Fundamentals-style context and lens scores.",
  engineCap4Title: "Quality",
  engineCap4Body: "Quality factors with plain-language rationale.",
  engineCap5Title: "Growth",
  engineCap5Body: "Comparable growth scores per holding.",
  engineCap6Title: "Momentum",
  engineCap6Body: "Trend and momentum on charts and scores.",
  engineAiTitle: "Explained insights",
  engineAiBody: "What changed, why it matters, and which factors drove it.",
  aiProBadge: "Alpha Pro",
  whyNowEyebrow: "Why now",
  whyNowTitle: "More data. Same hard decisions.",
  whyNowIntro: "More apps and quotes - but your book stays fragmented without context.",
  whyNowProblem1Title: "Data overload",
  whyNowProblem1Body: "Screens multiply. Holdings stay split across accounts.",
  whyNowProblem2Title: "Fragmented brokers",
  whyNowProblem2Body: "No single view of exposure, concentration, or performance.",
  whyNowProblem3Title: "Missing context",
  whyNowProblem3Body: "Numbers alone do not say what deserves attention now.",
  whyNowResolution:
    "Alpha Investor unifies imports, market data, and explained analytics on the book you hold.",
  benefitsTitle: "Why investors choose Alpha Investor",
  benefitsIntro: "Built for long-term holders managing real money across brokers.",
  benefit1Title: "See total exposure",
  benefit1Body: "One view when holdings span multiple accounts.",
  benefit2Title: "Know concentration risk",
  benefit2Body: "Signals on mix and concentration - inform, not alarm.",
  benefit3Title: "Compare on one model",
  benefit3Body: "The same lens scale on every holding.",
  trustTitle: "Trust and security",
  trustIntro: "",
  trustSecurityTitle: "No broker credentials required",
  trustSecurityBody: "Import via export files - we never ask for trading passwords.",
  trustPrivacyTitle: "Privacy-first architecture",
  trustPrivacyBody: "Your portfolio data stays scoped to your account.",
  trustProcessingTitle: "Licensed market data",
  trustProcessingBody: "Quotes and reference data from licensed providers - not scraped broker sites.",
  trustPrivacyCta: "Read privacy policy",
  scaleTitle: "Built for scale",
  scaleIntro: "Infrastructure built so imports and data workloads grow with users.",
  scaleBullet1: "Multi-broker books across currencies",
  scaleBullet2: "Global equities and ETFs",
  scaleBullet3: "Analytics at portfolio sync scale",
  pricingEyebrow: "Pricing",
  pricingTitle: "Plans",
  pricingTagline: "Free core tracking. Alpha Pro adds the full intelligence layer.",
  pricingFreeName: "Free",
  pricingFreePrice: "$0",
  pricingFreeBullet1: "Portfolios, quotes, and charts.",
  pricingFreeBullet2: "Same privacy on your data.",
  pricingFreeBullet3: "Upgrade in-app when ready.",
  pricingProName: "Alpha Pro",
  pricingProBadge: "Full AI",
  pricingProPrice: "$10",
  pricingProPeriod: "/ month",
  pricingProBullet1: "Signals from your portfolio weights.",
  pricingProBullet2: "Five lenses with rationale.",
  pricingProBullet3: "Chart, context, and AI in one view.",
  pricingProBullet4: "New Pro features first.",
  pricingCtaPrimary: "Join Early Access",
  pricingCtaSecondary: "Learn More",
  pricingDisclaimerLine:
    "Educational software only - not investment advice. No return promises.",
  pricingFootnote: "Subscribe in the iOS app. Cancel anytime in device settings.",
  screensTitle: "See your portfolio clearly",
  screensIntro: "",
  galleryPortfolioInsightKicker: "Signals",
  galleryWalletValueKicker: "Performance",
  galleryWalletAllocationKicker: "Allocation",
  galleryChartKicker: "Momentum",
  galleryFiveLensesKicker: "Comparison",
  galleryFundamentalsKicker: "Valuation",
  galleryWalletAllocationTitle: "Allocation",
  galleryPortfolioInsightTitle: "Portfolio insight",
  galleryChartTitle: "Charts",
  galleryFiveLensesTitle: "Five lenses",
  galleryFundamentalsTitle: "Fundamentals",
  faqTitle: "FAQ",
  faq1Q: "Can I import portfolios from brokers?",
  faq1A:
    "Yes. Export positions from your broker and import the file in the app. No broker login or trading passwords required.",
  faq2Q: "How is my portfolio data handled?",
  faq2A:
    "Imports are privacy-first and scoped to your account. We do not train public models on your holdings. See our Privacy policy for details.",
  faq3Q: "Which markets are supported?",
  faq3A:
    "Major US and European listings today, with broader coverage as imports and symbol validation expand.",
  faq4Q: "Will Android be supported?",
  faq4A: "iOS is available now. Android is on the roadmap - join early access for updates.",
  faq5Q: "How does pricing work?",
  faq5A:
    "Free includes portfolios, quotes, and charts. Alpha Pro is $10/month in the App Store for the full explained intelligence layer.",
  ctaTitle: "Start with your real portfolio",
  ctaSub: "Join early access for product updates.",
  formConsent: "By joining, you agree we may email you about the product. See",
  formConsentLink: "Privacy",
  disclaimer:
    "Not investment, tax, or legal advice. Verify anything that would change your money.",
  roadmapTitle: "Platform roadmap",
  roadmapIntro: "Where the platform is heading.",
  roadmapFootnote: "Direction only - not commitments or dates.",
  roadmapPhase1Title: "Portfolio Tracking",
  roadmapPhase1Badge: "In progress",
  roadmapPhase1Body: "Live on iOS: unified books, quotes, and performance.",
  roadmapPhase2Title: "Broker Connectivity",
  roadmapPhase2Body: "More brokers and smoother imports across accounts.",
  roadmapPhase3Title: "Portfolio Intelligence",
  roadmapPhase3Body: "Allocation, risk, and explained analytics on your book.",
  roadmapPhase4Title: "Research Workflows",
  roadmapPhase4Body: "Deeper research on your portfolio - not generic screens.",
  roadmapPhase5Title: "Investment Operating System",
  roadmapPhase5Body: "Multi-broker tracking and analysis built to scale.",
} as const;
