/**
 * English marketing copy - source deck for product messaging.
 * Keep `messages/en.json` → `Home` (and related keys) aligned with this file;
 * Polish lives only in `messages/pl.json`.
 */
export const landingHome = {
  skipToContent: "Skip to content",
  ctaPrimary: "Join Early Access",
  ctaSecondary: "Learn More",
  eyebrow: "Portfolio analytics · iOS",
  headline: "Know what to do.",
  heroProof1: "Portfolio tracking",
  heroProof2: "Analytics",
  heroProof3: "Insights",
  subhead:
    "Track your portfolio, understand what changed, and make better investment decisions.",
  heroPrimaryCta: "Join Early Access",
  heroSecondaryCta: "Learn More",
  heroImageAlt:
    "Alpha Investor screen showing five lenses: trend, valuation, risk, growth, and momentum.",
  heroDeckWalletAlt: "Portfolio view with allocation and performance.",
  heroDeckChartAlt: "Instrument detail with chart and performance.",
  trustItem1: "Broker file imports",
  trustItem2: "Licensed market data",
  trustItem3: "Privacy-first",
  trustItem4: "Not investment advice",
  importsTitle: "Import your portfolio in minutes",
  importsIntro:
    "Upload a broker export and start tracking your investments instantly.",
  importsStep1Title: "Upload file",
  importsStep1Body: "Export from your broker—we map positions automatically.",
  importsStep2Title: "Portfolio created",
  importsStep2Body: "Your holdings appear in one book.",
  importsStep3Title: "Analytics available",
  importsStep3Body: "Allocation, performance, and insights turn on.",
  brokerXtb: "XTB",
  brokerIbkr: "Interactive Brokers",
  brokerDegiro: "DEGIRO",
  brokerT212: "Trading 212",
  brokerRevolut: "Revolut",
  brokerCsv: "CSV Imports",
  whyNowEyebrow: "Why now",
  whyNowTitle: "More data. Same hard decisions.",
  whyNowIntro:
    "More apps and quotes than ever—but portfolio truth stays fragmented without context tied to your book.",
  whyNowProblem1Title: "Data overload",
  whyNowProblem1Body: "Screens multiply. Your book stays split across accounts.",
  whyNowProblem2Title: "Fragmented brokers",
  whyNowProblem2Body: "No single view of exposure, concentration, or performance.",
  whyNowProblem3Title: "Missing context",
  whyNowProblem3Body: "Numbers alone do not say what deserves attention now.",
  whyNowResolution:
    "Alpha Investor unifies imports, market data, and explained analytics on the portfolio you actually hold.",
  platformTitle: "Portfolio tracking and analysis",
  platformIntro: "One book from broker exports—not a generic watchlist.",
  platformPillar1Title: "Connect your brokers",
  platformPillar1Body: "Import via export files. No broker passwords.",
  platformPillar2Title: "Enrich with market data",
  platformPillar2Body: "Quotes and reference data for every holding.",
  platformPillar3Title: "Understand with insights",
  platformPillar3Body: "Allocation, risk lenses, and explained signals on your weights.",
  dataEyebrow: "Infrastructure",
  dataTitle: "Market data infrastructure",
  dataIntro:
    "Licensed market data APIs power quotes, fundamentals, and symbol validation for every portfolio.",
  dataGrid1Title: "Historical prices",
  dataGrid1Body: "Performance context for holdings and your book.",
  dataGrid2Title: "Company fundamentals",
  dataGrid2Body: "Reference data for valuation lenses.",
  dataGrid3Title: "ETF & instrument metadata",
  dataGrid3Body: "Classification for mixed equity and fund books.",
  dataGrid4Title: "Instrument discovery",
  dataGrid4Body: "Search and validate symbols across major listings.",
  dataGrid5Title: "Portfolio analytics",
  dataGrid5Body: "Allocation and risk enrichment on the server.",
  dataGrid6Title: "Market-wide coverage",
  dataGrid6Body: "Built for many symbols per user, many users over time.",
  dataPartnerCta: "Data & API partnerships",
  dataVendorsLink: "For data vendors",
  dataFooterLine:
    "We do not resell raw data. Licensed feeds power portfolio intelligence for end users.",
  engineTitle: "Portfolio intelligence",
  engineIntro: "Analytics on your real weights—not a generic watchlist.",
  engineCap1Title: "Portfolio allocation",
  engineCap1Body: "Weights and drift across sectors and positions.",
  engineCap2Title: "Risk concentration",
  engineCap2Body: "Exposure flags tied to your book.",
  engineCap3Title: "Valuation",
  engineCap3Body: "Fundamentals-style context and lens scores.",
  engineCap4Title: "Quality",
  engineCap4Body: "Quality factors with plain-language rationale.",
  engineCap5Title: "Growth",
  engineCap5Body: "Comparable growth scores per holding.",
  engineCap6Title: "Momentum",
  engineCap6Body: "Trend and momentum on charts and scores.",
  engineAiTitle: "Explained insights",
  engineAiBody: "What changed, why it matters, and which factors drove it.",
  aiProBadge: "Alpha Pro",
  diffTitle: "More than a portfolio tracker",
  diffPoint1: "Track your holdings",
  diffPoint2: "Understand portfolio quality",
  diffPoint3: "Discover what deserves attention",
  benefitsTitle: "Built for active investors",
  benefitsIntro: "When you manage real money across brokers.",
  benefit1Title: "See total exposure",
  benefit1Body: "One view when holdings span multiple accounts.",
  benefit2Title: "Know concentration risk",
  benefit2Body: "Signals on mix and concentration—inform, not alarm.",
  benefit3Title: "Compare on one model",
  benefit3Body: "The same lens scale on every holding.",
  trustTitle: "Trust and data handling",
  trustIntro: "Sensitive holdings data—designed so you stay in control.",
  trustSecurityTitle: "Security",
  trustSecurityBody: "No broker passwords or trading OAuth.",
  trustPrivacyTitle: "Privacy",
  trustPrivacyBody: "No training public models on your portfolio.",
  trustProcessingTitle: "File processing",
  trustProcessingBody: "Privacy-first import; on-device parsing where supported.",
  trustPrivacyCta: "Read privacy policy",
  scaleTitle: "Built for scale",
  scaleIntro:
    "Early-stage today—built so imports and data workloads compound as users grow.",
  scaleBullet1: "Multi-broker books across currencies",
  scaleBullet2: "Global equities and ETFs",
  scaleBullet3: "Data and analytics at portfolio sync scale",
  stepsTitle: "How it works",
  step1Title: "Import your book",
  step1Body: "Broker export or manual positions.",
  step2Title: "We enrich holdings",
  step2Body: "Licensed quotes and validation on the server.",
  step3Title: "Review insights",
  step3Body: "Wallet and holding readouts—then you decide.",
  pricingEyebrow: "Pricing",
  pricingTitle: "Plans",
  pricingTagline: "$10/month for the full AI layer on your portfolio.",
  pricingFreeName: "Free",
  pricingFreePrice: "$0",
  pricingFreeBullet1: "Portfolios, quotes, and charts.",
  pricingFreeBullet2: "Same privacy on your data.",
  pricingFreeBullet3: "Upgrade in-app when ready.",
  pricingProName: "Alpha Pro",
  pricingProBadge: "Full AI",
  pricingProPrice: "$10",
  pricingProPeriod: "/ month",
  pricingProBullet1: "Signals from your portfolio weights.",
  pricingProBullet2: "Five lenses with rationale.",
  pricingProBullet3: "Chart, context, and AI in one view.",
  pricingProBullet4: "New Pro features first.",
  pricingCtaPrimary: "Join Early Access",
  pricingCtaSecondary: "Learn More",
  pricingDisclaimerLine:
    "Educational software only—not investment advice. No return promises.",
  pricingFootnote: "Subscribe in the iOS app. Cancel anytime in device settings.",
  screensTitle: "See your portfolio clearly",
  screensIntro: "",
  galleryPortfolioInsightKicker: "Signals",
  galleryWalletValueKicker: "Performance",
  galleryWalletAllocationKicker: "Allocation",
  galleryChartKicker: "Momentum",
  galleryFiveLensesKicker: "Comparison",
  galleryFundamentalsKicker: "Valuation",
  galleryWalletAllocationTitle: "Allocation",
  galleryPortfolioInsightTitle: "Portfolio insight",
  galleryChartTitle: "Charts",
  galleryFiveLensesTitle: "Five lenses",
  galleryFundamentalsTitle: "Fundamentals",
  faqTitle: "FAQ",
  faq1Q: "Is this financial advice?",
  faq1A: "No. Software and education only—you make trading and tax decisions.",
  faq2Q: "How do broker imports work?",
  faq2A: "Export from your broker and import in the app. No broker login required.",
  faq3Q: "Which brokers are supported?",
  faq3A: "XTB, IBKR, DEGIRO, Trading 212, Revolut, and CSV—more over time.",
  faq4Q: "Where does market data come from?",
  faq4A: "Licensed providers on our servers—not other users' data.",
  faq5Q: "What does the AI add?",
  faq5A: "Explained readouts on your book. Alpha Pro adds the full layer.",
  faq6Q: "Which platforms are supported?",
  faq6A: "iOS today. Android on the roadmap.",
  faq7Q: "How does pricing work?",
  faq7A: "Free for core tracking. Alpha Pro is $10/month in the App Store.",
  faq8Q: "Do you train public models on my portfolio?",
  faq8A: "No. Insights are generated for your account only.",
  faq9Q: "What happens after I join the waitlist?",
  faq9A: "Occasional product email. Unsubscribe anytime.",
  faq10Q: "Are you a broker?",
  faq10A: "No. We do not hold assets or route orders.",
  faq11Q: "Data or API partnership?",
  faq11A: "Email partners@alphainvestor.app.",
  faq12Q: "Is my data secure?",
  faq12A: "Privacy-first imports and account-scoped insights. See Privacy policy.",
  ctaTitle: "Start with your real portfolio",
  ctaSub: "Download on iOS or join early access for updates.",
  formConsent: "By joining, you agree we may email you about the product. See",
  formConsentLink: "Privacy",
  disclaimer:
    "Not investment, tax, or legal advice. Verify anything that would change your money.",
  roadmapTitle: "Platform roadmap",
  roadmapIntro: "Where the platform is heading.",
  roadmapFootnote: "Direction only—not commitments or dates.",
  roadmapPhase1Title: "Portfolio Tracking",
  roadmapPhase1Badge: "In progress",
  roadmapPhase1Body: "Live on iOS: unified books, quotes, and performance.",
  roadmapPhase2Title: "Broker Connectivity",
  roadmapPhase2Body: "More brokers and smoother imports across accounts.",
  roadmapPhase3Title: "Portfolio Intelligence",
  roadmapPhase3Body: "Allocation, risk, and explained analytics on your book.",
  roadmapPhase4Title: "Research Workflows",
  roadmapPhase4Body: "Deeper research on your portfolio—not generic screens.",
  roadmapPhase5Title: "Investment Operating System",
  roadmapPhase5Body: "Multi-broker tracking and analysis built to scale.",
  appStoreBadgeSmall: "Download on the",
  appStoreBadgeLarge: "App Store",
  appStoreBadgeAria: "Download Alpha Investor on the App Store",
} as const;
